#pragma once

#ifdef RGB_MATRIX_HUE_STEP
#	undef RGB_MATRIX_HUE_STEP
#endif
#ifdef RGB_MATRIX_SAT_STEP
#	undef RGB_MATRIX_SAT_STEP
#endif
#ifdef RGB_MATRIX_VAL_STEP
#	undef RGB_MATRIX_VAL_STEP
#endif

#define RGB_DI_PIN E2
#define DRIVER_LED_TOTAL 9
#define RGB_MATRIX_HUE_STEP 1
#define RGB_MATRIX_SAT_STEP 1
#define RGB_MATRIX_VAL_STEP 1
#define RGB_DISABLE_WHEN_USB_SUSPENDED true					// Switch off lights on suspend
#define RGB_MATRIX_LED_FLUSH_LIMIT 10						// Update frequency (ms). This is basically 100fps
#define RGB_MATRIX_LED_PROCESS_LIMIT DRIVER_LED_TOTAL		// Number of LEDs to update per animation step
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 255					// Max brightness

#if 0 // Enable or disable key reactive light timeout
#	define RGB_DISABLE_AFTER_TIMEOUT 5						// Time (s) before switching off LEDs
#	define RGB_MATRIX_KEYREACTIVE_ENABLED					// Monitor for global key events to store when last pressing any key
//#	define RGB_MATRIX_KEYPRESSES							// Monitor Key Presses. Only configure one of RGB_MATRIX_KEYPRESSES or RGB_MATRIX_KEYRELEASES
#	define RGB_MATRIX_KEYRELEASES							// Monitor Key Releases. Only configure one of RGB_MATRIX_KEYPRESSES or RGB_MATRIX_KEYRELEASES
#endif

#if 0 // Enable or disable typing heatmap
#	define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#else
#	define DISABLE_RGB_MATRIX_TYPING_HEATMAP
#endif

// Disable RGB Light Animations
#undef RGBLIGHT_ANIMATIONS
#undef RGBLIGHT_EFFECT_BREATHING
#undef RGBLIGHT_EFFECT_RAINBOW_MOOD
#undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
#undef RGBLIGHT_EFFECT_SNAKE
#undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
#undef RGBLIGHT_EFFECT_RGB_TEST
#undef RGBLIGHT_EFFECT_ALTERNATING
#undef RGBLIGHT_USE_TIMER

// Disable RGB Matrix Animations
#define DISABLE_RGB_MATRIX_ALPHAS_MODS
#define DISABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#define DISABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#define DISABLE_RGB_MATRIX_BAND_SAT
#define DISABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#define DISABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#define DISABLE_RGB_MATRIX_BAND_VAL
#define DISABLE_RGB_MATRIX_BREATHING
#define DISABLE_RGB_MATRIX_CYCLE_ALL
#define DISABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define DISABLE_RGB_MATRIX_CYCLE_OUT_IN
#define DISABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#define DISABLE_RGB_MATRIX_CYCLE_PINWHEEL
#define DISABLE_RGB_MATRIX_CYCLE_SPIRAL
#define DISABLE_RGB_MATRIX_CYCLE_UP_DOWN
#define DISABLE_RGB_MATRIX_DIGITAL_RAIN
#define DISABLE_RGB_MATRIX_DUAL_BEACON
#define DISABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#define DISABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#define DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define DISABLE_RGB_MATRIX_RAINBOW_BEACON
#define DISABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#define DISABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#define DISABLE_RGB_MATRIX_RAINDROPS
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#define DISABLE_RGB_MATRIX_SOLID_SPLASH
#define DISABLE_RGB_MATRIX_SOLID_MULTISPLASH
#define DISABLE_RGB_MATRIX_SPLASH
#define DISABLE_RGB_MATRIX_MULTISPLASH
